artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "C:\Users\jeet5\Downloads\Branching-tutorial-master\Branching-tutorial-master\cat-dog-data.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
